-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Recipe CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS Unit CASCADE;
DROP TABLE IF EXISTS IngredientOfARecipe CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS TagOfARecipe CASCADE;
DROP TABLE IF EXISTS FavoriteRecipe CASCADE;
